---
title: "Aditya Pratap Manker-200101012-DSA Assignment"
author: "Aditya Pratap Manker"
date: "18/12/2020"
output: word_document
---

---

## 
## R Introduction
```{r introduction}

#Creating Simple Objects and Doing Calculations

a = 10             #Value 10 is assigned to Variable a
a
b = 20
b

class(a)          # Data Type of variable a
 
a = "Hello World"
class(a)
a = TRUE
class(a)
a = FALSE
class (a)

#Object Assignments and Simple Calculations
x = 20
y = 15
x+y               #Sum of x and y
x-y
x*y
x/y
sqrt(x)
x^y
exp(x)
log(x, base=exp(1))
log10(x)
help("log")      #Using R Help
factorial(x)
cos(x)
abs(x)
```
## 
## FUNCTIONS

```{r Functions}
getwd()       #Get Working Directory

# Functions in R
divider = function(x,y) {
  result = x/y
  print(result)
}
divider(20,10)
divider (100,25)

# Multiplication
multiply = function(a,b){
  return (a * b)       #Directly returns the value
}
multiply(26,15)
multiply (25,30)


#Variables Names are CASE SENSITIVE
Z=10
z=24

Z       #Prints value for Z


#CONCATENATION AND ARRAYS

f <- c(1,2,3,4,5)
f = c(1,2,3,4,5)
f
f+4            #Adds 4 to each element

d = f / 4
d

f+d


```
##
## Data Types in R

```{R Data Types}

x = 10
class(x)
# Numeric - Integer and Decimal - (R)- Integer (Whole Number) and Numeric (Float - Decimal)
i = 5L # L - Integer
class(i)
is.integer(i)
is.numeric(x)



# Logical - TRUE (1) and FALSE (0)
#R understands value of TRUE as 1 and FALSE as 0
TRUE * 5      
FALSE * 5

K = TRUE
class(K)
is.logical(K)

# Date - Starting Date (1970) - Numeric Value.
# In R - 1 Jan 1970
# Date - mm/dd/yyyy
# POSIXct - Date plus Time.

date1 = as.Date("2012-06-28")
# as.Date()# Auto complete # How to enter
# ? as.Date # help
date1
class (date1)
as.numeric(date1)

#POSIXct - Date and Time
date2 = as.POSIXct("2012-06-28 17:42")
date2
class(date2)
as.numeric(date2)

```

## VECTORS

```{r vectors}

v = c(1,2,3,4,5)
s = v*2
s

#Vector Operation
d = v-2
d
f = v /2
f
sqrt(f)

numb = c(7,8,9,3,4)
numb


length(numb)   #Size of the vector

numb[c(1,3)]   #Access 1st and 3rd element

numb = c(7,8,9,3,4)

numb[5]=10    #Assigns 10 to 5th position

numb

sort(numb)  #Arranges in ascending order

#Give Names to Vector!
c(One = "a", Two = "y", Last = "r") # Name-Value pair
# You can Name the vector after creating vector as well!
w = 1:3
names(w) = c("a","b","c")
w

```
## 
## DATAFRAMES

```{r dataframes}
x = 10:1
y = -4:5
q = c("Hockey","Football","Baseball","Curlin","Rugby","Lacrosse",
      "Basketball","Tennis","Cricket","Soccer")
theDF = data.frame(x,y,q) # this would create a 10x3 data.frame with x, y and q as variable names
theDF

# Checking the dimensions of the DF.
nrow(theDF)
ncol(theDF)
dim(theDF)
names (theDF)
names(theDF)[3]
rownames(theDF)

# Head and Tail
head(theDF)
head(theDF, n=7)
tail(theDF)

class(theDF)

# Assigning Names
theDF = data.frame (First=x, Second =y, Sport = q)
theDF

# Accessing Individual Column using $

theDF$Sport # gives the third column named Sport

# Accessing Specific row and column
theDF[3,2] # 3rd row and 2nd Column
theDF[3,2:3] # 3rd Row and column 2 thru 3
theDF[c(3,5), 2]# Row 3&5 from Column 2; 
# since only one column was selected, it was returned as vector and hence no column names in output.

# Rows 3&5 and Columns 2 through 3
theDF[c(3,5), 2:3]

theDF[ ,3] # Access all Rows for column 3
theDF[ , 2:3]

theDF[2,]# Access all columns for Row 2
theDF[2:4,]

#Another way to create data frames
custData = data.frame(name=c("Tom", "Sally", "Sue"),
                      age=c(43, 28, 42),
                      stringsAsFactors=T)

custData



```

## 
## FACTORS

```{R FACTORS}

#Create a factor vector
q2 = c(q,"Hockey","Lacrosse","Hockey","Water Polo","Hockey","Lacrosse")
q2
class(q2)
as.numeric(q2)

class(q2)

#Creating another factor vector
direction = c("Up", "Down", "Left", "Right", "Left", "Up")
factorDir = factor(direction)
factorDir


is.factor(factorDir)  #Checks if it is a factor
is.factor(direction)
factorDir   #Only unique values

# A Factor object contains levels which store all possible
# values
levels(x=factorDir)


# You can define your levels and their orders
dow = c("Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday")

wDays = c("Tuesday", "Thursday", "Monday")

wdFact = factor(x=wDays, levels=dow, ordered=T)

wdFact

```

##
## MISSING DATA
```{r missing data}
# NA - Missing data - Missing Value
#NA is the value which is mission in the vector
z = c(1,2,NA,8,3,NA,3)
#z = c(1,2,na,8,3,na,3) -> R does not understand 'na'
z
# "is.na" tests each element of a vector for missingness
is.na(z)

# ...If used inside a vector, it simply disappears! Let's see...
z= c(1,NULL,3)
z
x = c(1,NA,3)
x 
# Notice, here the "NULL" didnot get stored in "z", infact "z" has only length of 2!
length(z) #NULL is not treated as NA and is not stored
length(x)

# Assigning NULL and checking!
d = NULL
is.null(d)

```
##
## MATRICES
```{r matrices}

# Create a Matrix with a single column
matrix1 = matrix(data=c(1,2,3,4))
matrix1

# Create a matrix with defined rows and columns
matrix2 = matrix(data=c(1,2,3,4), nrow=2, ncol=2)
matrix2

# You can also fill by row (You can use T or TRUE)
matrix3 = matrix(data=c(1,2,3,4), nrow=2, ncol=2, byrow=T)
matrix3

# Get a Matrix dimension
dim(matrix3)

# A value at row, column
matrix3[1,2]

# Get a whole row
matrix3[1,]

# Get a whole column
matrix3[,2]

# Combine vectors to make a Matrix
matrix4 = rbind(1:3, 4:6, 7:9)
matrix4

# Get 2nd and 3rd row
matrix4[2:3,]

# Get 2nd and 3rd row by ommitting the 1st
matrix4[-1,]

# Change the first value
matrix4[1,1] = 0
matrix4

# Change the 1st row
matrix4[1,] = c(10,11,12)
matrix4

#creating few more matrices
A = matrix(1:10, nrow=5)# Create a 5x2 matrix
B = matrix(21:30, nrow=5)#Create another 5x2 matrix 
C = matrix (21:40, nrow=2)#Create another 2x10 matrix
D = matrix(41:45, ncol = 5) #Creates 1*5 matrix
D
A
B
C

nrow(A)
ncol(A)
dim(A)

# Add the values of the matrices A and B
A+B

# Multiply Them (Vector Multiplication!)
A
B
A*B  # A = 5x2 and B = 5x2

#See if the elements are equal
A == B

# Matrix Multiplication(MM. A is 5x2. B is 5x2. B-transpose is 2x5
A %*% t(B)

# Naming the Columns and Rows 
colnames(A)
rownames(A)
colnames(A)= c("Left","Right")
rownames(A)= c("1st","2nd","3rd","4th","5th")
colnames(B)
rownames(B)
colnames(B)= c("First","Second")
rownames(B)= c("One","Two","Three","Four","Five")
colnames(C)
rownames(C)

colnames(C) = LETTERS [1:10]
rownames(C) = c("Top", "Bottom")

# Matrix Multiplication. A is 5x2 and C is 2x10
dim(A)
dim(C)
t(A)
A %*% C

```

##
## ARRAYS

```{r arrays}
theArray = array(1:12, dim=c(2,3,2))# Total Elements = R x C x OD
theArray
theArray [1, ,]# Accessing all elements from Row 1, all columns, all outer dimensions & build C x OD (R x C)
theArray[1, ,1]# Accessing all elements from Row 1, all columns, first outer dimension 
theArray[, ,1]# Accessing all rows, all columns, first outer dimension

# Array with Four Outer Dimensions (OD)
theArray_4D = array(1:32, dim=c(2,4,4))
theArray_4D
theArray_4D [1, ,]
theArray_4D[1, ,1]
theArray[, ,1]

```

##
## LIST
```{r list}
list(1,2,3)# creates a three element list
list(c(1,2,3))# creates a single element(vector with three elements)
list3 = list(c(1,2,3), 3:7)# create two element list
# first is three elements vector, next is five element vector.
list3
# The same can be written as
(list3 = list(c(1,2,3), 3:7))

# Two Element list
# First element is data.frame and next is 10 element vector
list(theDF, 1:10)# theDF is already created in previous exercise!

# Three element list
list5 = list(theDF, 1:10, list3)
list5

#Naming List (similar to column name in data.frame) 
names(list5)= c("data.frame", "vector","list")
names(list5)
list5
#Naming using "Name-Value" pair
list6 = list(TheDataFrame = theDF, TheVector = 1:10, TheList = list3)
names(list6)
list6

# Creating an empty list
(emptylist = vector(mode="list", length =4))

# Accessing individual element of a list - Double Square Brackets
# specify either element number or name
list5[[1]]
list5[["data.frame"]]
list5[[1]]$Sport
list5[[1]][,"Second"]
list5[[1]][,"Second", drop = FALSE]

# LENGTH OF LIST
length(list5)
names(list5)
list5
```

##
## READ AND WRITE FILES

```{r read write files}
myPeople = read.table("People.txt.txt",
                      header=T, sep=" ",
                      na.strings="`",
                      stringsAsFactors=F)
myPeople



# Add another person
addname = data.frame(fname="Rahul",
                         lname="Dravid",
                         sex="M")
myPeople = rbind(myPeople, addname)
myPeople
# Update a record
myPeople[5,2] = "Smith"
myPeople
# Update the file by supplying the data.frame,
# the file to write, seperator, na, whether to
# quote strings, whether to include row numbers
write.table(x=myPeople, "People.txt.txt",
            sep=" ", na="`",
            quote=F, row.names=F)

# Get 1st 3 records
head(myPeople, 3)

# Get remaining records
tail(myPeople, 3)
```
```{r stats}
x = sample(x=1:100, size = 20, replace = TRUE)
x # the output of "x" is a vector of data

# Simple Arithmetic Mean
mean(x)

# Calculate Mean when Missing Data is found
y = x # copy x to y
y[sample(x=1:100, size = 20, replace = FALSE )] = NA # Null Values
y
y = sample(x=1:100, size = 20, replace = FALSE) 
y

mean(y)# Will give NA!

# Remove missing value(s)and calculate mean
mean(y, na.rm=TRUE) # Now, it will give the mean value

# Weighted Mean
Grades = c(95,72,87,66)
Weights = c(1/2, 1/4, 1/8, 1/8)
mean(Grades)# Simple Arithmetic mean
weighted.mean(x = Grades, w = Weights)# Weighted Mean

#Variance
var(x)
#Calculating Variance using formula!
sum((x-mean(x))^2)/ (length(x)-1)

# Standard Deviation
sqrt(var(x))
sd(x)
sd(y)
sd(y, na.rm=TRUE)

# Other Commonly Used Functions
min(x)
max(x)
median(x)
min(y)
min(y, na.rm=TRUE)

# Summary Statistics
summary(x)
summary(y)

# Quantiles
quantile(x, probs = c(0.25, 0.75)) # Calculate 25th and 75th Quantile
quantile(x, probs = c(0.1,0.25,0.5, 0.75,0.99))

quantile(y, probs = c(0.25, 0.75)) # Calculate 25th and 75th Quantile
quantile(y, probs = c(0.25, 0.75), na.rm = TRUE)

# Correlation and Covariance

#library(ggplot2)# require(ggplot2)
#head(economics)# Built-in dataset in ggplot2 package
#cor(economics$pce, economics$psavert) #pce-Personal Consumption Expenditure;psavert -Personal Savings Rate

# To compare correlation for Multiple variables
#cor(economics[, c(2,4:6)])

# Display Correlation in Different Format!

# Lets install the required package and load them onto this R environment for executing!!!

# Load the "reshape" package
#install.packages("reshape2")
#require(reshape2)
# Also load the Scales package for some extra plotting features
#install.packages("scales")
#library(scales)

#econCor = cor(economics [ , c(2,4:6)])
# use "melt()" to change into long format
#?melt() # Help on melt function
#econMelt = melt(econCor, varnames = c("x" ,"y"), #value.name = "Correlation")
# Order it according to correlation
#econMelt = econMelt[order(econMelt$Correlation),]
# Display the melted data
#econMelt

# Let's Visualize Correlation
## Plot it with ggplot
# Initialize the plot with x and y on the respective axes
#ggplot(econMelt,aes (x=x, y=y),geom_tile(aes(fill = #Correlation)),scale_fill_gradient2(low = muted("red"), mid = "white", high = #"steelblue",guide = guide_colorbar(ticks=FALSE, #barheight=10), limit=c(-1,1), theme_minimal(), #labs(x= NULL, y=NULL)))
```
## 
## HEATMAP

```{r heatmap}
# Correlation

# Prepare the Data
mydata <- mtcars[, c(1,3,4,5,6,7)]
head(mydata)

# Compute the correlation matrix - cor()
cormat <- round(cor(mydata),2)
head(cormat)

# Create the correlation heatmap with ggplot2
# The package reshape is required to melt the correlation matrix.
library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)

#The function geom_tile()[ggplot2 package] is used to visualize the correlation matrix :
library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

#Doesnot Look Great.. Let's Enhance the viz!

#Get the lower and upper triangles of the correlation matrix
## a correlation matrix has redundant information. We'll use the functions below to set half of it to NA.

# Get lower triangle of the correlation matrix
get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}

upper_tri <- get_upper_tri(cormat)
upper_tri

#  Finished correlation matrix heatmap
## Melt the correlation data and drop the rows with NA values
# Melt the correlation matrix
library(reshape2)
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Heatmap
library(ggplot2)
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()


# negative correlations are in blue color and positive correlations in red. 
# The function scale_fill_gradient2 is used with the argument limit = c(-1,1) as correlation coefficients range from -1 to 1.
# coord_fixed() : this function ensures that one unit on the x-axis is the same length as one unit on the y-axis.

# Reorder the correlation matrix

# This section describes how to reorder the correlation matrix according to the correlation coefficient. 
# This is useful to identify the hidden pattern in the matrix. 
# hclust for hierarchical clustering order is used in the example below.

reorder_cormat <- function(cormat){
  # Use correlation between variables as distance
  dd <- as.dist((1-cormat)/2)
  hc <- hclust(dd)
  cormat <-cormat[hc$order, hc$order]
}

# Reorder the correlation matrix
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)
# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Create a ggheatmap
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()
# Print the heatmap
print(ggheatmap)

#Add correlation coefficients on the heatmap

## Use geom_text() to add the correlation coefficients on the graph
## Use a blank theme (remove axis labels, panel grids and background, and axis ticks)
## Use guides() to change the position of the legend title

ggheatmap + 
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.justification = c(1, 0),
    legend.position = c(0.6, 0.7),
    legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                               title.position = "top", title.hjust = 0.5))
```

##
## HYPOTHESIS TESTING

```{r hypothesis}
# T-tests
# Dataset: Tips dependents on...
data(tips, package = "reshape2")
head(tips)
str(tips)
write.csv(tips, "C:/Users/91996/Desktop/IMT GHAZIABAD/TERM 2/Data Science  & Analytics/DSA Assignment/tips.csv", row.names = FALSE)

# Gender
unique(tips$sex)
#Day of the week
unique(tips$day)

#One Sample t-test - ONE GROUP [Two Tail. Ho:Mean = 2.5]
t.test(tips$tip, alternative = "two.sided", mu=2.5)

#One Sample t-test - Upper Tail. Ho:Mean LE 2.5
t.test(tips$tip, alternative = "greater", mu=2.5)

# Two Sample T-test - TWO GROUP
t.test(tip ~ sex, data = tips, var.equal = TRUE)

#Paired Two-Sample T-Test 
# Dataset: Heights of Father and Son (Package:UsingR)
install.packages("UsingR", repo="https://cran.us.r-project.org")
require(UsingR)
head(father.son)
write.csv(father.son, "C:/Users/91996/Desktop/IMT GHAZIABAD/TERM 2/Data Science  & Analytics/DSA Assignment/father_son.csv", row.names = FALSE)

#ANOVA  - Comparing Multiple Groups
# Tip by the Day of the Week
str(tips)
tipAnova = aov(tip ~ day, tips)
summary(tipAnova)

```

##
## LINEAR REGRESSION

```{r linearregression}
# Simple Linear Regression (SLR)
# Dataset: father.son. 
# Using fathers' heights to predit sons' heights using SLR.
# Fathers height as predictor(Indep - X) and 
# Son's height as the response /Target(Dep - Y)
require(UsingR)
require(ggplot2)
head(father.son)
ggplot(father.son, aes(x=fheight, y=sheight))+geom_point()+
  geom_smooth(method="lm")+labs(x="Fathers", y="Sons")
heightsLM = lm(sheight ~ fheight, data = father.son)
heightsLM
summary(heightsLM)
```

